configs_dir = "config"

[urls]
homebrew_install = "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"

[symlinks.common]
bash.bashrc = "$HOME/.bashrc"
zsh.zshrc = "$HOME/.zshrc"
fish."config.fish" = "$HOME/.config/fish/config.fish"
fish.fish_plugins = "$HOME/.config/fish/fish_plugins"
git.gitconfig = "$HOME/.gitconfig"
git.global_ignore = "$HOME/.global_ignore"
nvim.old_vimrc = "$HOME/.config/nvim/init.vim"
#nvim."init.lua" = "$HOME/.config/nvim/init.lua"
vim.vimrc = "$HOME/.vimrc"
tmux."tmux.conf" = "$HOME/.tmux.conf"
kitty."kitty.conf" = "$HOME/.config/kitty/kitty.conf"
intellij.ideavimrc = "$HOME/.ideavimrc"
vscode."keybindings.json" = "$HOME/.vscode/keybindings.json"
vscode."settings.json" = "$HOME/.vscode/settings.json" 
bin = "$HOME/.bin"

[symlinks.Darwin]
hammerspoon."init.lua" = "$HOME/.hammerspoon/init.lua"
homebrew.Brewfile = "$HOME/.Brewfile"

[[downloads]]
url = "https://raw.githubusercontent.com/Hammerspoon/Spoons/master/Spoons/ReloadConfiguration.spoon.zip"
directory = "$HOME/.hammerspoon/Spoons/"
name = "ReloadConfiguration.spoon"
unzip = true

[[downloads]]
url = "https://raw.githubusercontent.com/Hammerspoon/Spoons/master/Spoons/Caffeine.spoon.zip"
directory = "$HOME/.hammerspoon/Spoons"
name = "Caffeine.spoon"
unzip = true

[[downloads]]
url = "https://github.com/Hammerspoon/Spoons/raw/master/Spoons/WindowHalfsAndThirds.spoon.zip"
directory = "$HOME/.hammerspoon/Spoons"
name = "WindowHalfsAndThirds.spoon"
unzip = true

[[downloads]]
url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
directory = "$HOME/.local/share/nvim/site/autoload/"
name = "plug.vim"
unzip = false
