#!/bin/bash

files="vimrc zshrc oh-my-zsh"
dotfiles_dir=~/dotfiles
dotfiles_backup_dir=~/dotfiles_backup
ohmyzsh_dir=~/.oh-my-zsh

cd

if [ -d "$dotfiles_dir" ]; then
  mkdir $dotfiles_backup_dir
  cp -r $dotfiles_dir $dotfiles_backup_dir
fi

for file in $files; do
  #if [ -e "$file" ]; then
  #fi
  echo "Creating symlinks for dotfiles"
  ln -s $dotfiles_dir/$file ~/.$file
done


chsh -s /bin/zsh

vundle


