#!/bin/bash

files="vimrc zshrc oh-my-zsh"
dotfiles_dir=~/dotfiles
dotfiles_backup_dir=~/dotfiles_backup

cd

if [ -d "$dotfiles_dir" ]; then
  #mkdir $dotfiles_backup_dir
  echo "true"
  #cp -r $dotfiles_dir $dotfiles_backup_dir
fi

for file in $files; do
  if [ ! -e ".$file" ]; then
    echo "Creating symlinks for dotfiles"
    ln -s $dotfiles_dir/$file ~/.$file
  fi
done
