#!/bin/bash

git submodule init
git submodule update

SYMLINKS="vimrc zshrc gitconfig oh-my-zsh vim"
DOTFILES_DIR="$HOME/dotfiles"
BACKUP_SUFFIX="orig"
OHMYZSH_THEME="ifahad7.zsh-theme"

echo "This script makes ZSH your default shell"
# make zsh your default shell
chsh -s /bin/zsh

for SYMLINK in $SYMLINKS; do

  if [ -e "$HOME/.$SYMLINK" ]; then

    i="0"
    while [ -e "$HOME/$SYMLINK.$BACKUP_SUFFIX" ]
    do
      i=$[$i+1]
      BACKUP_SUFFIX="orig$i"
    done

    echo "Oh ... You have $SYMLINK, I'll back it up for you!!"
    echo -e "Copying symlink $HOME/.$SYMLINK -> $HOME/$SYMLINK.$BACKUP_SUFFIX\n"

    mv $HOME/.$SYMLINK $HOME/$SYMLINK.$BACKUP_SUFFIX

  fi

  echo "Creating symlinks $HOME/.$SYMLINK -> $DOTFILES_DIR/$SYMLINK"
  ln -s $DOTFILES_DIR/$SYMLINK $HOME/.$SYMLINK


done


# install plug
if [ ! -e "$HOME/.vim/autoload/plug.vim" ]; then
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# install vim plugins
vim +PlugInstall +qal

# Congifure vim-gist
git config --global github.user "ifahad7"

if [ $DOTFILES_DIR/$OHMYZSH_THEME ]; then
  cp $DOTFILES_DIR/$OHMYZSH_THEME $DOTFILES_DIR/oh-my-zsh/themes/
fi
