#!/bin/bash

SYMLINKS="zshrc gitconfig oh-my-zsh vimrc vim config/nvim"
for SYMLINK in $SYMLINKS; do
  if [ -e "$HOME/.$SYMLINK" ]; then
    echo "---- Deleting $HOME/.$SYMLINK"
    rm -rf "$HOME/.$SYMLINK"
  else
    echo "---- $HOME/.$SYMLINK already removed"
  fi
done
